In [1]:
# Import classes
import numpy as np
from sklearn import datasets

# Load and parse the data file
iris = datasets.load_iris()
iris_X = iris.data
iris_y = iris.target
np.unique(iris_y)

# Split iris data in train and test data
# A random permutation, to split the data randomly 
np.random.seed(0)
indices = np.random.permutation(len(iris_X))
iris_X_train = iris_X[indices[:-10]]
iris_y_train = iris_y[indices[:-10]]
iris_X_test  = iris_X[indices[-10:]]
iris_y_test  = iris_y[indices[-10:]]

In [2]:
# Import classes
import numpy as np
# import matplotlib.pyplot as plt
from sklearn import datasets

# Load and parse the data file
iris = datasets.load_iris()
iris_X = iris.data
iris_y = iris.target
np.unique(iris_y)

# Split iris data in train and test data
# A random permutation, to split the data randomly 
np.random.seed(0)
indices = np.random.permutation(len(iris_X))
iris_X_train = iris_X[indices[:-10]]
iris_y_train = iris_y[indices[:-10]]
iris_X_test  = iris_X[indices[-10:]]
iris_y_test  = iris_y[indices[-10:]]

# Create figure
# plt.figure(1)

# Train a k-nearest-neighbor model
# Create and fit a k-nearest-neighbor classifier
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(iris_X_train, iris_y_train)


# Evaluate model on test instances and comput test error
from sklearn.metrics import accuracy_score
print knn.predict(iris_X_test)
accuracy_score_knn = accuracy_score(iris_y_test, knn.predict(iris_X_test))
print "{:10.20f}".format(accuracy_score_knn)


# 1
# Linear SVC
# Create and fit a LinearSVC classifier
from sklearn.svm import SVC, LinearSVC
linearsvc = LinearSVC()
linearsvc = linearsvc.fit(iris_X_train, iris_y_train)
accuracy_score_linearsvc = accuracy_score(iris_y_test, linearsvc.predict(iris_X_test))
print "{:10.20f}".format(accuracy_score_linearsvc)

#
# # 2
# # Light SVC
# from gat.classifiers import SVC_Light
# svc_light = SVC_Light(kernel = 'linear')
# svc_light = svc_light.fit(iris_X_train, iris_y_train)
# accuracy_score_svclight = accuracy_score(iris_y_test, svc_light.predict(iris_X_test))
# print "{:10.20f}".format(accuracy_score_svclight)


# 3
# Random forest classifier
import nltk
# from nltk.classify.scikitlearn import SklearnClassifier
# random_forest = SklearnClassifier()
# random_forest.fit(iris_X_train, iris_y_train)
# accuracy_score_randomforest = accuracy_score(iris_y_test, random_forest.predict(iris_X_test))
# print "{:10.20f}".format(accuracy_score_randomforest)

# 4
# Ada boost classifer
from sklearn.ensemble import AdaBoostClassifier
ada_boost = AdaBoostClassifer()
ada_boost.fit(iris_X_train, iris_y_train)
accuracy_score_adaboost = accuracy_score(iris_y_test, ada_boost.predict(iris_X_test))
print "{:10.20f}".format(accuracy_score_adaboost)

[1 2 1 0 0 0 2 1 2 0]
0.90000000000000002220
0.90000000000000002220


NameError: name 'AdaBoostClassifer' is not defined

In [3]:
# Import classes
import numpy as np
# import matplotlib.pyplot as plt
from sklearn import datasets

# Load and parse the data file
iris = datasets.load_iris()
iris_X = iris.data
iris_y = iris.target
np.unique(iris_y)

# Split iris data in train and test data
# A random permutation, to split the data randomly
np.random.seed(0)
indices = np.random.permutation(len(iris_X))
iris_X_train = iris_X[indices[:-10]]
iris_y_train = iris_y[indices[:-10]]
iris_X_test  = iris_X[indices[-10:]]
iris_y_test  = iris_y[indices[-10:]]

# Create figure
# plt.figure(1)

# Train a k-nearest-neighbor model
# Create and fit a k-nearest-neighbor classifier
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(iris_X_train, iris_y_train)


# Evaluate model on test instances and comput test error
from sklearn.metrics import accuracy_score
print knn.predict(iris_X_test)
accuracy_score_knn = accuracy_score(iris_y_test, knn.predict(iris_X_test))
print "{:10.20f}".format(accuracy_score_knn)


# 1
# Linear SVC
# Create and fit a LinearSVC classifier
from sklearn.svm import SVC, LinearSVC
linearsvc = LinearSVC()
linearsvc = linearsvc.fit(iris_X_train, iris_y_train)
accuracy_score_linearsvc = accuracy_score(iris_y_test, linearsvc.predict(iris_X_test))
print "{:10.20f}".format(accuracy_score_linearsvc)

#
# # 2
# # Light SVC
# from gat.classifiers import SVC_Light
# svc_light = SVC_Light(kernel = 'linear')
# svc_light = svc_light.fit(iris_X_train, iris_y_train)
# accuracy_score_svclight = accuracy_score(iris_y_test, svc_light.predict(iris_X_test))
# print "{:10.20f}".format(accuracy_score_svclight)


# 3
# Random forest classifier
import nltk
from nltk.classify.scikitlearn import SklearnClassifier
random_forest = SklearnClassifier()
random_forest.fit(iris_X_train, iris_y_train)
accuracy_score_randomforest = accuracy_score(iris_y_test, random_forest.predict(iris_X_test))
print "{:10.20f}".format(accuracy_score_randomforest)

# 4
# Ada boost classifer
# from sklearn.ensemble import AdaBoostClassifier
# ada_boost = AdaBoostClassifer()
# ada_boost.fit(iris_X_train, iris_y_train)
# accuracy_score_adaboost = accuracy_score(iris_y_test, ada_boost.predict(iris_X_test))
# print "{:10.20f}".format(accuracy_score_adaboost)

[1 2 1 0 0 0 2 1 2 0]
0.90000000000000002220
0.90000000000000002220


TypeError: __init__() takes at least 2 arguments (1 given)

In [4]:
# Import classes
import numpy as np
# import matplotlib.pyplot as plt
from sklearn import datasets

# Load and parse the data file
iris = datasets.load_iris()
iris_X = iris.data
iris_y = iris.target
np.unique(iris_y)

# Split iris data in train and test data
# A random permutation, to split the data randomly
np.random.seed(0)
indices = np.random.permutation(len(iris_X))
iris_X_train = iris_X[indices[:-10]]
iris_y_train = iris_y[indices[:-10]]
iris_X_test  = iris_X[indices[-10:]]
iris_y_test  = iris_y[indices[-10:]]

# Create figure
# plt.figure(1)

# Train a k-nearest-neighbor model
# Create and fit a k-nearest-neighbor classifier
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(iris_X_train, iris_y_train)


# Evaluate model on test instances and comput test error
from sklearn.metrics import accuracy_score
print knn.predict(iris_X_test)
accuracy_score_knn = accuracy_score(iris_y_test, knn.predict(iris_X_test))
print "{:10.20f}".format(accuracy_score_knn)


# 1
# Linear SVC
# Create and fit a LinearSVC classifier
from sklearn.svm import SVC, LinearSVC
linearsvc = LinearSVC()
linearsvc = linearsvc.fit(iris_X_train, iris_y_train)
accuracy_score_linearsvc = accuracy_score(iris_y_test, linearsvc.predict(iris_X_test))
print "{:10.20f}".format(accuracy_score_linearsvc)

#
# # 2
# # Light SVC
# from gat.classifiers import SVC_Light
# svc_light = SVC_Light(kernel = 'linear')
# svc_light = svc_light.fit(iris_X_train, iris_y_train)
# accuracy_score_svclight = accuracy_score(iris_y_test, svc_light.predict(iris_X_test))
# print "{:10.20f}".format(accuracy_score_svclight)


# 3
# Random forest classifier
import nltk
from nltk.classify.scikitlearn import SklearnClassifier
random_forest = SklearnClassifier()
random_forest.fit(iris_X_train, iris_y_train)
accuracy_score_randomforest = accuracy_score(iris_y_test, random_forest.predict(iris_X_test))
print "{:10.20f}".format(accuracy_score_randomforest)

# 4
# Ada boost classifer
# from sklearn.ensemble import AdaBoostClassifier
# ada_boost = AdaBoostClassifer()
# ada_boost.fit(iris_X_train, iris_y_train)
# accuracy_score_adaboost = accuracy_score(iris_y_test, ada_boost.predict(iris_X_test))
# print "{:10.20f}".format(accuracy_score_adaboost)

[1 2 1 0 0 0 2 1 2 0]
0.90000000000000002220
0.90000000000000002220


TypeError: __init__() takes at least 2 arguments (1 given)

In [5]:
# Import classes
import numpy as np
# import matplotlib.pyplot as plt
from sklearn import datasets

# Load and parse the data file
iris = datasets.load_iris()
iris_X = iris.data
iris_y = iris.target
np.unique(iris_y)

# Split iris data in train and test data
# A random permutation, to split the data randomly
np.random.seed(0)
indices = np.random.permutation(len(iris_X))
iris_X_train = iris_X[indices[:-10]]
iris_y_train = iris_y[indices[:-10]]
iris_X_test  = iris_X[indices[-10:]]
iris_y_test  = iris_y[indices[-10:]]

# Create figure
# plt.figure(1)

# Train a k-nearest-neighbor model
# Create and fit a k-nearest-neighbor classifier
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(iris_X_train, iris_y_train)


# Evaluate model on test instances and comput test error
from sklearn.metrics import accuracy_score
print knn.predict(iris_X_test)
accuracy_score_knn = accuracy_score(iris_y_test, knn.predict(iris_X_test))
print "{:10.20f}".format(accuracy_score_knn)


# 1
# Linear SVC
# Create and fit a LinearSVC classifier
from sklearn.svm import SVC, LinearSVC
linearsvc = LinearSVC()
linearsvc = linearsvc.fit(iris_X_train, iris_y_train)
accuracy_score_linearsvc = accuracy_score(iris_y_test, linearsvc.predict(iris_X_test))
print "{:10.20f}".format(accuracy_score_linearsvc)

#
#  2
#  Light SVC
# from gat.classifiers import SVC_Light
# svc_light = SVC_Light(kernel = 'linear')
# svc_light = svc_light.fit(iris_X_train, iris_y_train)
# accuracy_score_svclight = accuracy_score(iris_y_test, svc_light.predict(iris_X_test))
# print "{:10.20f}".format(accuracy_score_svclight)


# 3
# Random forest classifier
# import nltk
# from nltk.classify.scikitlearn import SklearnClassifier
# random_forest = SklearnClassifier()
# random_forest.fit(iris_X_train, iris_y_train)
# accuracy_score_randomforest = accuracy_score(iris_y_test, random_forest.predict(iris_X_test))
# print "{:10.20f}".format(accuracy_score_randomforest)

# 4
# Ada boost classifer
# from sklearn.ensemble import AdaBoostClassifier
# ada_boost = AdaBoostClassifer()
# ada_boost.fit(iris_X_train, iris_y_train)
# accuracy_score_adaboost = accuracy_score(iris_y_test, ada_boost.predict(iris_X_test))
# print "{:10.20f}".format(accuracy_score_adaboost)

# 5
# LogisticRegression Classifier
from sklearn.linear_model import LogisticRegression
logistic_regression = LogisticRegression()
logistic_regression = logistic_regression.fit(iris_X_train, iris_y_train)
accuracy_score_logistic = accuracy_score(iris_y_test, logistic_regression.predict(iris_X_test))
print "{:10.20f}".format(accuracy_score_logistic)


[1 2 1 0 0 0 2 1 2 0]
0.90000000000000002220
0.90000000000000002220
0.90000000000000002220


In [1]:
# Cross-validation evaluation
from sklearn.model_selection import cross_val_score
linearsvc = LinearSVC()
linearsvc = linearsvc.fit(iris_X_train, iris_y_train)
scores_linearsvc = cross_val_score(linearsvc, iris.data, iris.target, cv=5)

ImportError: No module named model_selection

In [1]:
from sklearn.model_selection import cross_val_score


ImportError: No module named model_selection

In [2]:
from sklearn import cross_validation

In [3]:
# Cross-validation evaluation
from sklearn import cross_validation
scores_linearsvc = cross_val_score(linearsvc, iris.data, iris.target, scoring="f1_macro")
print "{:10.20f}".format(scores_linearsvc)

NameError: name 'cross_val_score' is not defined

In [4]:
scores_linearsvc = cross_val_score(linearsvc, iris.data, iris.target, scoring="f1_macro")
print "{:10.20f}".format(scores_linearsvc)

NameError: name 'cross_val_score' is not defined

In [5]:
from sklearn import cross_validation
from sklearn import metrics
scores_linearsvc = cross_val_score(linearsvc, iris.data, iris.target, scoring="f1_macro")
print "{:10.20f}".format(scores_linearsvc)

NameError: name 'cross_val_score' is not defined

In [6]:
from sklearn import cross_validation
from sklearn import metrics
scores_linearsvc = cross_val_score(linearsvc, iris.data, iris.target, scoring="f1_macro")
print "{:10.20f}".format(scores_linearsvc)

NameError: name 'cross_val_score' is not defined

In [1]:
from sklearn import cross_validation
from sklearn import metrics
scores_linearsvc = cross_validation.cross_val_score(linearsvc, iris.data, iris.target, scoring="f1_macro")
print "{:10.20f}".format(scores_linearsvc)

NameError: name 'linearsvc' is not defined

In [2]:
# Import classes
import numpy as np
# import matplotlib.pyplot as plt
from sklearn import datasets

# Load and parse the data file
iris = datasets.load_iris()
iris_X = iris.data
iris_y = iris.target
np.unique(iris_y)

# Split iris data in train and test data
# A random permutation, to split the data randomly
np.random.seed(0)
indices = np.random.permutation(len(iris_X))
iris_X_train = iris_X[indices[:-10]]
iris_y_train = iris_y[indices[:-10]]
iris_X_test  = iris_X[indices[-10:]]
iris_y_test  = iris_y[indices[-10:]]

# Create figure
# plt.figure(1)

# Train a k-nearest-neighbor model
# Create and fit a k-nearest-neighbor classifier
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(iris_X_train, iris_y_train)


# Evaluate model on test instances and comput test error
from sklearn.metrics import accuracy_score
print knn.predict(iris_X_test)
accuracy_score_knn = accuracy_score(iris_y_test, knn.predict(iris_X_test))
print "{:10.20f}".format(accuracy_score_knn)


# 1
# Linear SVC
# Create and fit a LinearSVC classifier
from sklearn.svm import SVC, LinearSVC
linearsvc = LinearSVC()
linearsvc = linearsvc.fit(iris_X_train, iris_y_train)
accuracy_score_linearsvc = accuracy_score(iris_y_test, linearsvc.predict(iris_X_test))
print "{:10.20f}".format(accuracy_score_linearsvc)

[1 2 1 0 0 0 2 1 2 0]
0.90000000000000002220
0.90000000000000002220


In [3]:
# 5
# LogisticRegression Classifier
from sklearn.linear_model import LogisticRegression
logistic_regression = LogisticRegression()
logistic_regression = logistic_regression.fit(iris_X_train, iris_y_train)
accuracy_score_logistic = accuracy_score(iris_y_test, logistic_regression.predict(iris_X_test))
print "{:10.20f}".format(accuracy_score_logistic)


# Cross-validation evaluation
from sklearn import cross_validation
from sklearn import metrics
scores_linearsvc = cross_validation.cross_val_score(linearsvc, iris.data, iris.target, scoring="f1_macro")
print "{:10.20f}".format(scores_linearsvc)

0.90000000000000002220


ValueError: Unknown format code 'f' for object of type 'str'

In [4]:
# Cross-validation evaluation
from sklearn import cross_validation
from sklearn import metrics
scores_linearsvc = cross_validation.cross_val_score(linearsvc, iris.data, iris.target, scoring="f1_macro")
print "{:10.20f}".format(scores_linearsvc)

ValueError: Unknown format code 'f' for object of type 'str'

In [5]:
scores_linearsvc.mean()

array([ 1.        ,  0.92156863,  0.9791463 ])

In [6]:
scores_linearsvc.mean()

0.96690497639264239

In [7]:
from sklearn import cross_validation
from sklearn import metrics
scores_linearsvc = cross_validation.cross_val_score(linearsvc, iris.data, iris.target, scoring="f1_macro")
print "{:10.20f}".format(scores_linearsvc.mean())

0.96690497639264239016


In [8]:
print "{LinearSVC cross_validation score:10.20f}".format(scores_linearsvc.mean())

KeyError: 'LinearSVC cross_validation score'

In [9]:
print "LinearSVC cross_validation score: " + "{:10.20f}".format(scores_linearsvc.mean())

LinearSVC cross_validation score: 0.96690497639264239016


In [10]:
accuracy_score_logistic = cross_validation.cross_val_score.accuracy_score(logistic_regression, iris.data, iris.target, scoring="f1_macro")
print "LogisticRegression cross_validation score: " + "{:10.20f}".format(scores_linearsvc.mean())

AttributeError: 'function' object has no attribute 'accuracy_score'

In [11]:
scores_logistic = cross_validation.cross_val_score.accuracy_score(logistic_regression, iris.data, iris.target, scoring="f1_macro")
print "LogisticRegression cross_validation score: " + "{:10.20f}"scores_logistic.format(.mean())

SyntaxError: invalid syntax (<ipython-input-11-1278238ed9bc>, line 2)

In [12]:
print "LogisticRegression cross_validation score: " + "{:10.20f}".format(.mean())

SyntaxError: invalid syntax (<ipython-input-12-8b8eeb086ad1>, line 1)

In [13]:
print "LogisticRegression cross_validation score: " + "{:10.20f}".format(scores_logistic.mean())

NameError: name 'scores_logistic' is not defined

In [14]:
scores_logistic = cross_validation.cross_val_score.accuracy_score(logistic_regression, iris.data, iris.target, scoring="f1_macro")
print "LogisticRegression cross_validation score: " + "{:10.20f}".format(scores_logistic.mean())

AttributeError: 'function' object has no attribute 'accuracy_score'

In [15]:
scores_logistic = cross_validation.cross_val_score(logistic_regression, iris.data, iris.target, scoring="f1_macro")
print "LogisticRegression cross_validation score: " + "{:10.20f}".format(scores_logistic.mean())

LogisticRegression cross_validation score: 0.94679557007988390804


In [16]:
scores_logistic.mean()

0.94679557007988391

In [17]:
scores_logistic

array([ 0.96064815,  0.92156863,  0.95816993])

In [18]:
knn = KNeighborsClassifier()
knn.fit(iris_X_train, iris_y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [19]:
from sklearn.metrics import accuracy_score
print knn.predict(iris_X_test)
accuracy_score_knn = accuracy_score(iris_y_test, knn.predict(iris_X_test))
print "{:10.20f}".format(accuracy_score_knn)

[1 2 1 0 0 0 2 1 2 0]
0.90000000000000002220


In [20]:
scores_knn = cross_validation.cross_val_score(knn, iris.data, iris.target, scoring="f1_macro")


In [21]:
scores_knn

array([ 0.98037518,  0.98037518,  1.        ])

In [22]:
scroes_knn.mean()

NameError: name 'scroes_knn' is not defined

In [23]:
scores_knn.mean()

0.98691678691678708

In [24]:
import matplotlib.pyplot as plt

In [25]:
plt.figure(1)

In [26]:
plt.plot(scores_knn.mean(), scores_linearsvc.mean(),  scores_logistic.mean())
plt.show()

ValueError: third arg must be a format string

In [27]:
plt.plot([1, 2, 3], [scores_knn.mean(), scores_linearsvc.mean(),  scores_logistic.mean()])
plt.ylabel("scores")
plt.show()

In [28]:
plt.scatter([1, 2, 3], [scores_knn.mean(), scores_linearsvc.mean(),  scores_logistic.mean()])
plt.ylabel("scores")
plt.show()

In [29]:
colors = np.random.rand(N)
area = np.pi * (15 * np.random.rand(N))**2
plt.scatter([1, 2, 3], [scores_knn.mean(), scores_linearsvc.mean(),  scores_logistic.mean()], s=area, c=colors, alpha=0.5)
plt.ylabel("scores")
plt.xlabel("knn    linearSVC      Logistic")
plt.show()


NameError: name 'N' is not defined

In [30]:
colors = np.random.rand(10)
area = np.pi * (15 * np.random.rand(10))**2
plt.scatter([1, 2, 3], [scores_knn.mean(), scores_linearsvc.mean(),  scores_logistic.mean()], s=area, c=colors, alpha=0.5)
plt.ylabel("scores")
plt.xlabel("knn    linearSVC      Logistic")
plt.show()

ValueError: Color array must be two-dimensional

In [31]:
colors = np.random.rand(3)
area = np.pi * (15 * np.random.rand(10))**2
plt.scatter([1, 2, 3], [scores_knn.mean(), scores_linearsvc.mean(),  scores_logistic.mean()], s=area, c=colors, alpha=0.5)
plt.ylabel("scores")
plt.xlabel("knn    linearSVC      Logistic")
plt.show()

In [32]:
plt.show()

In [33]:
plt.show()

In [34]:
colors = np.random.rand(3)
area = np.pi * (15 * np.random.rand(10))**2
plt.scatter([1, 2, 3], [scores_knn.mean(), scores_linearsvc.mean(),  scores_logistic.mean()], s=area, c=colors, alpha=0.5)
plt.ylabel("scores")
plt.xlabel("knn    linearSVC      Logistic")
plt.show()

In [35]:
scores_knn = cross_validation.cross_val_score(knn, iris.data, iris.target, scoring="f1_macro")
print "Knn cross_validation score: " + "{:10.20f}".format(scores_knn.mean())

Knn cross_validation score: 0.98691678691678708102
